### ISSUE TITLE
Package biblatex Error: Style 'ext-authoryear' not found

### ISSUE THREAD

**Issue by bennn** [rdicosmo/acmart-biblatex#1]
Hello, I'm having trouble building `main-acmauthoryear.tex` on my machine.

I cloned the repo, ran `pdflatex main-acmauthoryear.tex` and got this error about `ext-authoryear`:

```
! Package biblatex Error: Style 'ext-authoryear' not found.

See the biblatex package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.4 \RequireBibliographyStyle{ext-authoryear}
```

I'm using TeXLive 2017:
```
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.29; using libpng 1.6.29
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 3.04
```

**Comment by rdicosmo** [comment]
Indeed, I relied on biblatex-ext that is a rather recent package, that provides quite a few practical ways to customize biblatex
It can be dowloaded/installed from here https://ctan.org/tex-archive/macros/latex/contrib/biblatex-contrib/biblatex-ext

If this is really a blocker, we can try to avoid its use.

**Comment by rdicosmo** [comment]
Actually, it was kind of a no brainer to remove dependency on biblatex-ext, so I did it.
As an added bonus, biblatex-software files are also included for completeness, for people with a pre-2020 version of TeXLive (they can be removed if you have a recent version)
