### ISSUE TITLE
Decide what to do with repeated authors

### ISSUE THREAD

**Issue by rdicosmo** [rdicosmo/acmart-biblatex#2]
@borisveytsman I would need your advice to decide what to do with entries that have repeated same authors.

The standard behavious with biblatex in authoryear mode is to use a dash to indicate that it is the same author(s), see image below:
![acmauthoryear](https://user-images.githubusercontent.com/687807/154472380-e19c4210-e71c-4af6-ab75-f9a2b890ce7a.png)

While in the ACM bibtex implementation the same author(s) are repeated, see image below:
![acm-bibtex](https://user-images.githubusercontent.com/687807/154472413-d34ebbf2-a77a-47d9-8275-a73d4674d966.png)

Is it ok to keep the standard biblatex approach (first image), or should I adapt the style to reproduce exactly the behaviour of the original bibtex approach (second image)?

**Comment by rdicosmo** [comment]
The change is a no brainer (just add the dashed=false option to biblatex).
If we want to imitate exactly the original ACM bst behaviour, I'll add this as a default in the bbx file itself

**Comment by k4rtik** [comment]
I would prefer maximum compatibility between the bibtex and biblatex variants of acmart, so indeed dashed=false will be a great choice here.

**Comment by rdicosmo** [comment]
Ok, fixed in https://github.com/rdicosmo/acmart-biblatex/commit/ae0ab1846a9cadf3ca6a0911a6c13670dba8a6e6
