### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by borisveytsman** [rdicosmo/acmart-biblatex#7]
Greetings

Could you take a sample from https://github.com/borisveytsman/acmart/blob/primary/samples/samples.dtx and add code for, say, sample-sigconf-biblatex.tex?

**Comment by rdicosmo** [comment]
Thanks for the guidance, I'll do this!

**Comment by rdicosmo** [comment]
@borisveytsman here is a first stable proposal to integrate the biblatex styles in acmart is now available for testing/validation at https://github.com/rdicosmo/acmart/releases/tag/acmart-biblatex

It contains:

- the biblatex styles in the stable version developed with great help of @k4rtik and testing by @bennn
- a proposed addition to samples.dtx in the samples directory that produces two examples using biblatex (acmsmall-biblatex and sigconf-biblatex)
- a modified Makefile that handles all the new files
- a proposed addition to acmart.cls that contains a short explanation of the biblatex style files and their use

All this is based upon the latest version of acmart as of https://github.com/borisveytsman/acmart/commit/fd887a614829bb91b4b02e382394fd26d2641736

Looking forward to your feedback!

**Comment by k4rtik** [comment]
@rdicosmo this issue can now be closed, right?

**Comment by rdicosmo** [comment]
> @rdicosmo this issue can now be closed, right?

Indeed, with thanks to @borisveytsman for merging in master!
